### PR TITLE
Initial Go spec implementation

### PR DESCRIPTION
**Pull request by jrh3k5**
This proposes an implementation of a Go interface that conforms to the specification outlined [here](https://github.com/paradigmxyz/mesc/blob/6e52dfecfaa9ea653db8f7c67941c22771c43e8d/SPECIFICATION.md#reference-implementation).

There are numerous TODOs:

* `endpoints.go` has them since this is intended to be merely a stub to be filled in later by actual functionality
* Numerous files under the `model/` namespace have them to call attention to, if it is acceptable to continue implementing, the need to implement helper methods on these models to assist with the parsing and interpretation of the model data (e.g., resolution of formally-defined parameters from metadata `map[string]any` references)

One thing that I would urge to consider is, actually, spinning this out into its own repo (and to do the same for the existing Python and Rust implementations). This has a couple of benefits:

* The use of GitHub releases to version out the libraries would be easier than trying to maintain lockstep (e.g., do you create a version tag if there's a bug fix in the Go implementation, which creates 'empty' releases of the specification, Rust implementation, and Python implementation?)
* It is common within the Go ecosystem to use source code hosted on a GitHub instance as a dependency. Although this can be made to work with a Go module nested under a `go/` folder in the repository, this dependency resolution works best when the `go.mod` file is hosted at the root of the repository - and that would work best if the Go implementation was hosted in its own repo (to avoid questions of why, for example, there's a `go.mod` file at the root of a repo containing Rust and Python code).

### CODE REVIEW

**Comment by sslivkoff** [comment]
hi. thanks for the PR. this is a nice start of the mesc go implementation

my knowledge of go is limited but some comments:
- most of the types and function signatures look good and nearly complete. the only main interface function that is missing is `IsMescEnabled`. and there might need to be a few more error types
- `GetEndpointByName` should error if the given name is not found. but the other query functions should merely return nil if they do not find any query results.
- is it normal to include a `context` argument for functions that just retrieve data from a config file?
- passing `Profile` information to `GetEndpointByName` or `FindEndpoints` has no effect on the query. so for those it might be good to change the functions to only accepting an optional `RpcConfig` argument.

regarding separating the repos, this is definitely possible. but there are a few factors that support a monorepo:
- the plan is that the underlying MESC specification should be 100% finalized once v1.0 is reached. this will hopefully minimize any version incompatibilities or breaking changes across implementations
- there are other software projects that do well keeping multiple language implementations in a single repo. for example in the main [polars repo](https://github.com/pola-rs/polars/releases) there are separate tagged releases of rust vs python. the same could be done in the mesc repo. we have an easier task than polars, because none of the language implementations will be interdependent. they only depend on the abstract mesc specification which will be frozen
- are each of the following go constructs valid? is there other functionality besides these that would be lost or compromised by a monorepo arrangement?
    - `require ( github.com/paradigmxyz/mesc/go v1.0.32 )`
    - `go get github.com/paradigmxyz/mesc/go@v1.0.32`
    - `import "github.com/paradigmxyz/mesc/go"`

- releases could be tagged in the format `<language>-1.<major>.<minor>`. 1 to indicate it's mesc version 1.0. major for breaking changes and minor for other updates. single the implementations are used independently, releases for 1 language don't matter for the other languages

**Comment by jrh3k5** [comment]
@sslivkoff:

> the only main interface function that is missing is IsMescEnabled. and there might need to be a few more error types

I don't see that in [reference implementation](https://github.com/paradigmxyz/mesc/blob/6e52dfecfaa9ea653db8f7c67941c22771c43e8d/SPECIFICATION.md#reference-implementation); should this PR include an expansion to document that function, too?

> GetEndpointByName should error if the given name is not found. but the other query functions should merely return nil if they do not find any query results.

Can you help me understand the difference in behaviors of handling 'not found' situations? I'm happy to change things to return `nil` (or return a `bool` to indicate found/not found, or whatever pattern works best), but consistency in handling that situation seems best for ease of use of the functions.

> is it normal to include a context argument for functions that just retrieve data from a config file?

I'm of the persuasion that one should, by default, accept a `context.Context`. Even if there's no immediate use case, it allows us to later add in, say, functionality to make calls to external I/O or, if applicable, honor timeouts that are configured within the given context in case there's ever some kind of risk of a long-running or infinite loop process. I'd normally be concerned about function signature bloat by trying to "future-proof" like this, but, in this case, `context.Context` is such an integral part of the Go runtime that I think, overwhelmingly, a context will be available at time of invocation and, if not, it's pretty easy to add in a call to `context.Background()` when calling this.

> passing Profile information to GetEndpointByName or FindEndpoints has no effect on the query. so for those it might be good to change the functions to only accepting an optional RpcConfig argument.

My only concern with doing that is that, if the reference implementation evolves to allow for new search criteria, having the function signature accept only one type of configuration option makes it effectively impossible to passively add such functionality - whereas languages like Python get it easily with named parameters that can be specified with a default value. You're right that passing in a profile has no effect here, but, in the interest of keeping things passively expandable for future uses cases, I'd urge to keep the variadic slice as-is.

> regarding separating the repos, this is definitely possible. but there are a few factors that support a monorepo:

Mmm, that concept of versioning identifiers to include is an interesting idea. Bear with me, as my knowledge of Python is trivial, and my knowledge of Rust near-zero, but: do you produce downloaded packages / binaries from the repo, rather than host it directly from the repo itself? If so, I think that may be a key distinction between what `polars` is doing and what you're trying to achieve here with Go.

Go has [a specific versioning convention](https://go.dev/doc/modules/version-numbers) that expects a specific format for it to be able to handle things like available dependency updates, as well as being able to resolve the correct version if I do:

```
go get github.com/paradigmxyz/mesc/go@latest
```

As such, a versioning scheme that is like `go-v1.3.3` won't work because it breaks the expected format documented in the aforementioned link, and one can't do `v1.3.3-go`, because that will make Go think that it's a pre-release candidate with a `go` label.

Versioning in Go has good reasons for being what it is, but that doesn't change the fact that it can be a bit arduous and cumbersome to deal with.

**Comment by jrh3k5** [comment]
I've:

* updated the function signatures to return `nil` if nothing is found 
* added `IsMESCEnabled`
* updated `GetEndpointByName` to receive an instance of `*model.RPCConfig` instead of a variadic slice of options

I'm also comfortable with trying to make the monorepo work and, if it doesn't, exploring other options.

**Comment by sslivkoff** [comment]
awesome. interfaces and types look solid

**Comment by sslivkoff** [comment]
going to merge this now instead of waiting for completion because scopewise it might take a series of PR's to complete

**Pull request merged**
